apiVersion: v1
kind: ConfigMap
metadata:
  name: reader-config
data:
  PORT: "8081"
  MINIO_BUCKET: "books-epub"
  MINIO_USE_SSL: "false"
  # Cross-namespace service URLs
  BOOKSTORE_API_URL: "http://bookstore-service.bookstore.svc.cluster.local:8080"
